### ISSUE TITLE
Did you ever get this working?

### ISSUE THREAD

**Issue by IamDan77** [elvenpath/CambridgeAudioAzur351R-RS232toMqtt#1]
Just wondering if you ever got this working. I tried a few times  but could never get the return carriage working.
https://community.home-assistant.io/t/carrage-returns-rs232/195312

Would be great to get this working with ESPHome for a simple setup

**Comment by elvenpath** [comment]
@IamDan77 as a HA component, no, didn't get to that due to the lack of time. The only (extensive, I might say) tests where through MQTT, using some client.  And  it worked perfectly. But I don't see why a HA component based on this would not work. HA sends the command to MQTT and the ESP board grabs it and sends it to the serial port using [Serial.println](https://www.arduino.cc/reference/en/language/functions/communication/serial/println/) which ends the string with a carriage return character.  Unlike your implementation, mine uses the ESP to actually control the CA. You're using the PI as some kind of proxy, just passing on the commands from the HA component to the serial. 

Like it says in most of the replies you got, I also believe it's something in your specific to your implementation of the ssh command. I didn't see anything obvious and don't have access to my CA until the middle of August. If you don't manage to get it working by then I'll try to help you with debugging.

**Comment by IamDan77** [comment]
Thanks for the reply. One more quick question, what pins have you assigned in your code? Ill try and get it going in the next couple of days. Ive been looking to get this sorted for a long time now :)
Ohh and how hard is it to convert this to esphome?

**Comment by elvenpath** [comment]
I'm only using TX/RX to send/receive data using the RS232 converter (and GND/5V, of course). 
Don't know about esphome. I've not played that much with it.

**Comment by IamDan77** [comment]
So I have been pulling my hair out trying to work this out. I have been monitoring my MQTT traffic and I can see the topics being sent along with a serial monitor to watch the serial output everything seems good. However when I connect the 8266 to the amp I get nothing. I can control the amp using my USB to serial cable with termite. 

Any helpful suggestions?
![image](https://user-images.githubusercontent.com/15886476/123768715-eaace880-d90b-11eb-9245-5d8288c0817b.png)

**Comment by elvenpath** [comment]
Have you tried setting up logging to syslog and check the ESP debug messages? I use my Synology syslog service for it.

**Comment by IamDan77** [comment]
Ive tried getting syslog working on my synology but it doesnt seem to log anything. I enabled serial logging and can see messages being sent. Good.

I plug in the serial cable and publish a command the results can be seen below

![image](https://user-images.githubusercontent.com/15886476/123920745-a122d300-d9c9-11eb-9eb4-8956c93a86e4.png)

The amp is replying with #11,02 errors and flood the serial monitor untill it crashes

**Comment by elvenpath** [comment]
Seems fine . 11,02 it's an error message from the receiver. Am i missing anything?

**Comment by IamDan77** [comment]
Sorry I'm probably not being clear enough (I need more sleep:) ). I just need to step through, perhaps something will click in my brain

1) Laptop > USB to serial > amp. Works no #11,02 errors

2) Home Assistant MQTT publish > 8266 > RS232 Converter > USB to serial > Laptop using termite to read serial. Appears to be sending the correct codes.

3)  Home Assistant MQTT publish > 8266 > RS232 Converter > amp. While monitoring the 8266 with USB receives #11,02 until termite crashes.

Looking at number 3 and the pic above. It look as though the correct command gets sent and the correct return sent, is the #11,02 normal? 

I'm sorry for being a pest, but I appreciate your help.

**Comment by IamDan77** [comment]
I turned serial off in your sketch and managed to get syslog working. Success!!! I finally got it working. Thankyou so much!!

**Comment by elvenpath** [comment]
Oh, you had serial logging enabled while plugged into receiver? That was the problem, it was sending the debug messages to the receiver, not only commands. Glad you could make it work. Have fun with it!

**Comment by IamDan77** [comment]
Thanks again, now to figure out the best way to get it into Home Assistant
